### PR TITLE
Enable log publishing options

### PR DESCRIPTION
**Pull request by stjohnb**

### CODE REVIEW

**Review by OzTK — APPROVED** [review]

**Comment by OzTK** [comment]
^^ I don't count 😭

**Comment by fiunchinho** [comment]
Have you guys tested it?

**Comment by stjohnb** [comment]
Sorry for the delay. We did use it & it was working well. We have stopped using it again though so no problem if you'd prefer not to merge this. 
Setting up permissions between cloudwatch, ES and a lambda was taking too much time to automate so we ended up skipping it

**Comment by fiunchinho** [comment]
Ok, thanks anyway!

**Pull request closed without merging**
