### PR TITLE
Idempotency and change detection

### PR DESCRIPTION
**Pull request by shawnsi**
I've added idempotent behavior and change detection to this module.  I've tested thoroughly locally but please test your use cases if possible as well.

I also tacked on an update to make certain parameters optional when not required by the AWS API.

### CODE REVIEW

**Comment by fiunchinho** [comment]
Nice, thank you! But what do you think about these improvements?

```
    try:
        pdoc = json.dumps(module.params.get('access_policies'))
    except Exception as e:
        module.fail_json(msg='Failed to convert the policy into valid JSON: %s' % str(e))

    response = client.describe_elasticsearch_domain(DomainName=module.params.get('name'))
    status = response['DomainStatus']
    current_policy_dict = json.loads(status['AccessPolicies'])

    # Modify the provided policy to provide reliable changed detection
    policy_dict = module.params.get('access_policies')
    for statement in policy_dict['Statement']:
        if 'Resource' not in statement:
            # The ES APIs will implicitly set this
            statement['Resource'] = '%s/*' % status['ARN']
            pdoc = json.dumps(policy_dict)

    changed = False
    if (status['ElasticsearchClusterConfig'] != cluster_config) or (status['EBSOptions'] != ebs_options) or (
                status['SnapshotOptions'] != snapshot_options) or (current_policy_dict != policy_dict):
        changed = True

    try:
        if changed:
            response = client.update_elasticsearch_domain_config(
                    DomainName=module.params.get('name'),
                    ElasticsearchClusterConfig=cluster_config,
                    EBSOptions=ebs_options,
                    SnapshotOptions=snapshot_options,
                    AccessPolicies=pdoc,
            )
    except botocore.exceptions.ClientError as e:
        changed = True
        if e.response['Error']['Code'] == 'ResourceNotFoundException':
            response = client.create_elasticsearch_domain(
                DomainName=module.params.get('name'),
                ElasticsearchVersion=module.params.get('elasticsearch_version'),
                ElasticsearchClusterConfig=cluster_config,
                EBSOptions=ebs_options,
                SnapshotOptions=snapshot_options,
                AccessPolicies=pdoc,
            )

    module.exit_json(changed=changed, response=response)
```

I think the code is simpler this way. If you push these changes, I'll happily merge them!

**Comment by fiunchinho** [comment]
I'll do the changes. Thank you anyway!

**Comment by shawnsi** [comment]
@fiunchinho this would be easier to parse if there was a proper diff to look at.  It appears you made two changes though:

1) You moved the first try block after the describe API call and before the update.  This will cause problems as we need to catch a possible `ResourceNotFoundException` from the describe call.
2) You collapsed the if statements into a single condition.  I find this way less readable it violates [PEP8](https://www.python.org/dev/peps/pep-0008/).

Please reconsider my work as is.

**Comment by fiunchinho** [comment]
I see.
I'll keep it as it is. Thanks

**Pull request merged**
