### PR TITLE
Flesh out ValidationException error responses

### PR DESCRIPTION
**Pull request by sgi-tschaller**
Makes the ValidationException error response more useful. When I was learning to use this that error had me stumped for quite a while.

### CODE REVIEW

**Comment by fiunchinho** [comment]
Hi! Thank you for the pull request! Instead of adding yet another if, maybe we could just always print both the message and the code. What do you think?

**Comment by sgi-tschaller** [comment]
I suspect that is probably a better solution.

I didn't implement it that way because I do not know if all codes are guaranteed to have a message. If that is the case then I can definitely see the benefit in that.

Possibly I could test to see if there is an error message and if there is print both the error code and error message? It replace the if I was adding with another one, but keep it more generic.

**Comment by fiunchinho** [comment]
Yeah, let's try that!

**Comment by fiunchinho** [comment]
Any news on this @sgi-tschaller ?

**Comment by jhogendorn** [comment]
Just FYI this was resolved by my commit/pr.

**Pull request closed without merging**
